name: Java CI

on:
  push:
    branches:
      - main
      - Wilou

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
        
    - name: Clone JFreeChart repository at the same level
      run: git clone https://github.com/jfree/jfreechart.git ../jfreechart-master
      
    - name: Download JUnit JAR files
      run: |
        mkdir -p lib
        curl -L -o lib/junit-4.13.2.jar https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
        curl -L -o lib/hamcrest-core-1.3.jar https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

      
    - name: Compile Java code
      working-directory: TP1
      run: javac -cp .:src/main:../lib/* src/main/*.java

    - name: Compile JUnit test code
      run: javac -cp .:lib/*:TP1/src TP1/src/test/*.java

    - name: Run JUnit tests
      run: java -cp .:lib/*:TP1/src:TP1/src/main:TP1/src/test org.junit.runner.JUnitCore test.ExecutionTest test.TlsTest

